name: Build Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Qt 5 and mingw
        run: choco install qt5-default mingw --confirm -r --no-progress

      - name: Clone protobuf
        run: git clone https://github.com/protocolbuffers/protobuf

      - name: Install protobuf
        run: >
          cd protobuf/cmake;
          mkdir build;
          cd build;
          $install_path=Resolve-Path ../../;
          cmake ..
          -Dprotobuf_BUILD_SHARED_LIBS=ON
          -Dprotobuf_BUILD_EXAMPLES=OFF
          -Dprotobuf_BUILD_TESTS=OFF
          -Dprotobuf_WITH_ZLIB=ON
          -Dprotobuf_BUILD_PROTOC_BINARIES=ON
          -DCMAKE_INSTALL_PREFIX="$install_path";
          cmake --build . --parallel 4 --target install

      - name: Compile protobuf messages
        run: ./protobuf/bin/protoc.exe --proto_path ./src/proto --cpp_out ./src/proto feature.proto example.proto

      - name: Clone OpenCV
        run: >
          git clone --branch 4.5.3 --depth 1 https://github.com/opencv/opencv;
          git clone --branch 4.5.3 --depth 1 https://github.com/opencv/opencv_contrib

      - name: Compile OpenCV
        run: >
            cd opencv; 
            mkdir build; 
            cd build;
            $extra_path=Resolve-Path ../../opencv_contrib/modules;
            $install_path=Resolve-Path .;
            cmake .. 
            -DOPENCV_EXTRA_MODULES_PATH="$extra_path"
            -DBUILD_TESTS=OFF
            -DBUILD_PERF_TESTS=OFF ..
            -DCMAKE_BUILD_TYPE=RELEASE
            -DBUILD_EXAMPLES=OFF
            -DBUILD_DOCS=OFF
            -DBUILD_JAVA=OFF
            -DBUILD_opencv_apps=OFF
            -DBUILD_opencv_aruco=OFF
            -DBUILD_opencv_barcode=OFF
            -DBUILD_opencv_bgsegm=OFF
            -DBUILD_opencv_bioinspired=OFF
            -DBUILD_opencv_calib3d=OFF
            -DBUILD_opencv_datasets=OFF
            -DBUILD_opencv_dpm=OFF
            -DBUILD_opencv_dnn_superres=OFF
            -DBUILD_opencv_face=OFF
            -DBUILD_opencv_features2d=OFF
            -DBUILD_opencv_flann=OFF
            -DBUILD_opencv_fuzzy=OFF
            -DBUILD_opencv_gapi=OFF
            -DBUILD_opencv_highgui=ON
            -DBUILD_opencv_img_hash=OFF
            -DBUILD_opencv_intensity_transform=OFF
            -DBUILD_opencv_line_descriptor=OFF
            -DBUILD_opencv_mcc=OFF
            -DBUILD_opencv_objc_bindings_generator=OFF
            -DBUILD_opencv_objdetect=OFF
            -DBUILD_opencv_optflow=OFF
            -DBUILD_opencv_phase_unwrapping=OFF
            -DBUILD_opencv_photo=OFF
            -DBUILD_opencv_rgbd=OFF
            -DBUILD_opencv_saliency=OFF
            -DBUILD_opencv_shape=OFF
            -DBUILD_opencv_js_bindings_generator=OFF
            -DBUILD_opencv_freetype=OFF
            -DBUILD_opencv_stereo=OFF
            -DBUILD_opencv_stitching=OFF
            -DBUILD_opencv_structured_light=OFF
            -DBUILD_opencv_superres=OFF
            -DBUILD_opencv_surface_matching=OFF
            -DBUILD_opencv_text=OFF
            -DBUILD_opencv_videostab=OFF
            -DBUILD_opencv_viz=OFF
            -DBUILD_opencv_wechat_qrcore=OFF
            -DBUILD_opencv_ximgproc=OFF
            -DBUILD_opencv_xobjdetect=OFF
            -DBUILD_opencv_xphoto=OFF
            -DBUILD_opencv_xfeatures2d=OFF
            -DBUILD_opencv_world=ON
            -DCMAKE_INSTALL_PREFIX="$install_path";
            cmake --build . --parallel 4 --config Release --target install

      - name: Run QMake
        run: C:/Qt/5.15.2/mingw81_64/bin/qmake.exe -makefile -o Makefile DeepLabel.pro

      - name: Run Make
        run: mingw32-make -f Makefile.Release

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows-release
          path: ./release/deeplabel
